import streamlit as st
import google.generativeai as genai
import webbrowser

if "chat_data" not in st.session_state:
    st.session_state.chat_data=[]

API_key="AIzaSyAYE3L4uR9X7pwLWF-cOOCrv4lRj27J8Vg"

genai.configure(api_key=API_key)   #initiallize

model=genai.GenerativeModel("gemini-2.5-flash")
st.header(" 🚀 My AI bot")
st.subheader("ask anything... ❓ ")

user_input=st.chat_input("write your query")
if user_input:

    st.session_state.chat_data.append(("🙍🏻‍♂️",user_input))

    if "who build you" in user_input or "who make up" in user_input or "who developed you" in user_input:

        response="I am AI model , Generated by Navreet. "

        st.session_state.chat_data.append(("👾", response))

    elif "open youtube" in user_input:
        webbrowser.open(" https://www.youtube.com")

    elif "open google" in user_input:
        webbrowser.open(" https://www.google.com")
    
    elif user_input.endswith("in google") :
        webbrowser.open(" https://www.google.com/search?q=" + user_input.replace(" ","+"),new=2)


    else:
        response=model.generate_content(user_input,#generation_config={#"max_output_tokens":300,
                                                                #   "temperature":0.5,
                                                                #   "stop_sequence":"\n"}
                                                                  )
        st.session_state.chat_data.append(("👾", response.text))
    # st.write(response)

for key,data in st.session_state.chat_data:
    with st.chat_message(key):
        # st.markdown(data)
        if key=="🙍🏻‍♂️":
            st.markdown(f" 🔍:  {data}")
        else:    
            st.markdown(f" 💡 :  {data}")


            